from . import hr_leave
from . import res_company
from . import res_config_setting
from . import account_account
from . import hr_employee
from . import asset_management
from . import account_asset_asset
from . import project_project
from . import res_partner
from . import project_task
from . import project_task_type
from . import helpdesk_ticket
from . import mail_message
from . import incoming_mail_config
from . import hr_leave_type
from . import hr_leave